# Generated by Django 5.1.6 on 2025-02-12 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0002_organisation_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptoprice',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ['-created_at']},
        ),
    ]
